[package]
name = "shim"
version = "0.1.0"
authors = ["GregDavidson <greg.davidson+git@gmail.com>"]

[dependencies]
getopts = "0.2.10"
postgres = "0.8.8"
postgres_large_object = "0.3.1"
# lazy_static = "0.1.*"

# [dependencies.hyper]
# git = "https://github.com/hyperium/hyper"

[dependencies.tiny_http]
git = "https://github.com/frewsxcv/tiny-http"

# get latest
[dependencies.lazy_static]
git = "https://github.com/Kimundi/lazy-static.rs"